name: Continuous Integration
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '6.x'
      - run: npm install
      - run: npm test
