name: CD
on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  test:
    name: Test
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '6.x'
      - run: npm install
      - run: npm test

  publish:
    name: Publish
    runs-on: ubuntu-18.04
    needs: test
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '6.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm publish
        if: startsWith(github.ref, 'refs/tags/')
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
